### ISSUE TITLE
bidirectional flows question

### ISSUE THREAD

**Issue by ksyblast** [aabc/ipt-netflow#100]
Hello!
This is more a question or a feature request neither than a bug.

Is there a possibility (or any plans) for bidirectional flows (similar to Cisco ASA)? 
Is it also somehow possible to merge flows and NAT events (also like the ASA does)?

Thank you in advance.

**Comment by aabc** [comment]
Hi,

1. No plans.
2. What is merge of flows and nat events? There is flows and nat events and they go in single export stream.

**Comment by ksyblast** [comment]
Regarding p.2 - as I see, there are separate messages - ones containing NAT events and ones containing netflow data like octets and packets count. So we observe flows with netflow.octetDeltaCount field but without netflow.natEvent field. And vice versa - netflow messages containing NAT events do not contain filelds like netflow.octetDeltaCount. I am using netflow version 10. 
So it looks like there are two types of flows for every session - "classic" netflow and NAT event. Is it possible to "merge" them somehow to a single flow message?
Am I missing something?

**Comment by ksyblast** [comment]
Thank you.
Yes, ASA combines NAT events and makes bisectional flows. But as far as I see it's not RFC compliant. However me and my team are just wondering if there are any plans to implement the same here.
Thank you for your answers.

**Comment by aabc** [comment]
No plans for protocol which I didn't know even exists. I thought about bidirectional flows. But, there is potential problem with it. In Cisco devices, netflow generation is bound to the particular interface(s). In that case reverse flow is equal to forward flow with swapped interface ids. While in ipt-netflow, it's bound to iptables rules (and even in different chains with different visibility), it is possible that we can not detect reverse flow (in some chains) or assemble all reverse packets without loss, because, for example, output interface is not yet knows for forward packets and known for reverse packets, or packet for the same direction could arrive from different interfaces. Another example, packets could arrive from eth0, routed, and sent to correct mac address on eth0. In such case we could not distinguish forward flow from reverse flow, because only difference would be mac addresses. Of course there could be invented heuristics to workaround that.

**Comment by ksyblast** [comment]
Thank you for a complete answer. In fact these questions appeared because we were thinking to use the same dashboard and perform the same analysis for ASA netflow data and ipt-netflow. But there is no strong need for that actually.
