### ISSUE TITLE
ipt-netflow in upstream linux kernel?

### ISSUE THREAD

**Issue by taktv6** [aabc/ipt-netflow#165]
Hi,

I have a question regarding this project: Are there or have there been any plans to contribute ipt-netflow to the upsteam Linux kernel via netdev ML? If there are no plans: What are the reasons? If it was rejected: What are the reasons?
I'd really like to see this in vanilla Linux as it would make life a lot easier for many folks.

Thanks
Oliver

**Comment by aabc** [comment]
In ~2008 upstream maintainers was reluctant to even consider pure netflow v5 implementation, because they thought netflow v5 is not preferable in compare to IPFIX, and someone will implement IPFIX soon, and packet rates was low and they also thought solutions like NFLOG with user-space implementations would be enough. That was in 2008, I am not really remember well all details. After that we decided it would work good enough as independent module and we go with this decision.

Perhaps, there is not much user-base desire for netflow/ipfix exporter to be in the mainline kernel or it would be there long ago (not necessarily this implementation).

**Comment by taktv6** [comment]
These days it seems there is more focus on performance and enabling NFV like usage of linux. Would you mind if I'd check with netdev ML if they would be interested in a patch and me deriving maybe a pure IPFIX patch based on your module? Of course I'd make sure your name and a reference to this project would be in the kernel source.

**Comment by aabc** [comment]
@taktv6 Of course you can ask. Not even need to ask my permission for the code reuse, since this is GPL licensed.

**Comment by taktv6** [comment]
Sure. License wise you're absolutely right. I just want to be polite :)

Thanks!

**Comment by aabc** [comment]
Can you post here link to netdev discussion if it will happen?
