### ISSUE TITLE
Incorrect PPS reported on CentOS 7

### ISSUE THREAD

**Issue by microlinux** [aabc/ipt-netflow#53]
I am running the latest version of ipt_NETFLOW in promisc mode on CentOS 7 (3.10.0-327.4.5.el7.x86_64) The netflow data being reported is showing the right bandwidth levels, but PPS being reported is almost exactly 50% of what it really is.

/proc/net/stat/ipt_netflow shows the same anomaly.

I have verified that iptables itself is seeing the "real" number of packets.

**Comment by aabc** [comment]
ipt_NETFLOW does not report PPS. What do you mean?

**Comment by microlinux** [comment]
Sorry, to clarify - my netflow collector (nfcapd) reports show PPS at 50% of the actual value. Initially I thought it was a problem with it's interpretation of data - but the PPS shown in /proc/net/stat/ipt_netflow essentially matches what the collector calculates:

cat /proc/net/stat/ipt_netflow

[...]
Rate: 89382314 bits/sec, 4602 packets/sec; Avg 1 min: 107991399 bps, 5253 pps; 5 min: 103915476 bps, 4981 pps
[...]

PPS is reported at 5253, but the actual rate hitting the ipt_NETFLOW monitor (as reported by the switch port it is attached to) is about 13000 PPS (a 1 minute average as well). I calculate 13000 PPS from iptables stats also.

Is the PPS reported by /proc/net/stat/ipt_netflow insignificant in relation to netflow data generated, or could I be interpreting what it represents incorrectly?

**Comment by aabc** [comment]
`Packets/sec` rate in `/proc/net/stat/ipt_netflow` is just [EWMA](https://en.wikipedia.org/wiki/Moving_average#Exponential_moving_average) **estimator** and should not be used for any accounting.

Amount of packets reported in netflow/ipfix exported data and in `traffic <pkt>` column in `/proc/net/stat/ipt_netflow` is precise values and should match iptables' `pkts` counters (`iptables -L -n -v -x`), and interface packet counters (if all is properly configured).

EWMA estimator have its properties. It should converge to actual rate if rate is _steady_, but otherwise it will fluctuate deviating (lagging) from actual values (it's "exponentially weighted" after all).

**Comment by microlinux** [comment]
I see thanks. 

I will verify if the _traffic <pkt>_ column matches iptables' counters.

**Comment by aabc** [comment]
Feel free to report your results here.

**Comment by microlinux** [comment]
Just wanted to report back that the _traffic [pkt]_ field does match the iptables counters. Thanks again for clarifying what the various counters mean, looks like I probably have a collector issue to investigate.

**Comment by aabc** [comment]
If you have packet drops you should also add `drop: <pkt>`. All packets entering module is accounted in stat, in _traffic_ or in _drops_. If match is triggered, iptables counters are incremented too. There is nowhere packets could lost not being accounted. Counters may not match exactly, of course, because you can not read them exactly in same time (traffic goes). Example:

```
~# iptables -L -n -v -x |grep NETFLOW|summ 1; \
  grep ^Total /proc/net/stat/ipt_netflow|egrep -o traffic:[^,]+|egrep -o [0-9]+
256376476633
256376477290
```
(`summ 1` is arithmetic sum of first column, of output of iptables counters.) Here, difference is only 657 packets becasue `/proc/net/stat/ipt_netflow` is read few ms later.

**Comment by aabc** [comment]
> field does match the iptables counters

Ah, I misread as 'does not'. Well, thanks!
